title: "Ali El Gohary"
description: "Data Scientist & Software Engineer Portfolio"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

nav-headers:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/

